# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/capstone/arm_gpio/arm_gpio.srcs/sources_1/bd/gpio_test/ip/gpio_test_processing_system7_0_0/gpio_test_processing_system7_0_0.xci
# IP: The module: 'gpio_test_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/capstone/arm_gpio/arm_gpio.gen/sources_1/bd/gpio_test/ip/gpio_test_processing_system7_0_0/gpio_test_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_test_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/capstone/arm_gpio/arm_gpio.srcs/sources_1/bd/gpio_test/ip/gpio_test_processing_system7_0_0/gpio_test_processing_system7_0_0.xci
# IP: The module: 'gpio_test_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/capstone/arm_gpio/arm_gpio.gen/sources_1/bd/gpio_test/ip/gpio_test_processing_system7_0_0/gpio_test_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_test_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
