# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/capstone/shared_mem/shared_mem.srcs/sources_1/bd/shared_mem/ip/shared_mem_axi_bram_ctrl_0_0/shared_mem_axi_bram_ctrl_0_0.xci
# IP: The module: 'shared_mem_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/capstone/shared_mem/shared_mem.gen/sources_1/bd/shared_mem/ip/shared_mem_axi_bram_ctrl_0_0/shared_mem_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_mem_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/capstone/shared_mem/shared_mem.srcs/sources_1/bd/shared_mem/ip/shared_mem_axi_bram_ctrl_0_0/shared_mem_axi_bram_ctrl_0_0.xci
# IP: The module: 'shared_mem_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/capstone/shared_mem/shared_mem.gen/sources_1/bd/shared_mem/ip/shared_mem_axi_bram_ctrl_0_0/shared_mem_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shared_mem_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
