# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gpio_test/gpio_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test || ORIG_REF_NAME==gpio_test} -quiet] -quiet

# IP: bd/gpio_test/ip/gpio_test_processing_system7_0_0/gpio_test_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test_processing_system7_0_0 || ORIG_REF_NAME==gpio_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/gpio_test/ip/gpio_test_axi_gpio_0_1/gpio_test_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test_axi_gpio_0_1 || ORIG_REF_NAME==gpio_test_axi_gpio_0_1} -quiet] -quiet

# IP: bd/gpio_test/ip/gpio_test_xbar_0/gpio_test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test_xbar_0 || ORIG_REF_NAME==gpio_test_xbar_0} -quiet] -quiet

# IP: bd/gpio_test/ip/gpio_test_ps7_0_axi_periph_0/gpio_test_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==gpio_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/gpio_test/ip/gpio_test_rst_ps7_0_100M_0/gpio_test_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==gpio_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/gpio_test/ip/gpio_test_axi_gpio_0_2/gpio_test_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test_axi_gpio_0_2 || ORIG_REF_NAME==gpio_test_axi_gpio_0_2} -quiet] -quiet

# IP: bd/gpio_test/ip/gpio_test_auto_pc_0/gpio_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==gpio_test_auto_pc_0 || ORIG_REF_NAME==gpio_test_auto_pc_0} -quiet] -quiet

# XDC: d:/capstone/arm_gpio/arm_gpio.gen/sources_1/bd/gpio_test/gpio_test_ooc.xdc
