# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/shared_mem/shared_mem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shared_mem || ORIG_REF_NAME==shared_mem} -quiet] -quiet

# IP: bd/shared_mem/ip/shared_mem_processing_system7_0_0/shared_mem_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shared_mem_processing_system7_0_0 || ORIG_REF_NAME==shared_mem_processing_system7_0_0} -quiet] -quiet

# IP: bd/shared_mem/ip/shared_mem_axi_bram_ctrl_0_0/shared_mem_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shared_mem_axi_bram_ctrl_0_0 || ORIG_REF_NAME==shared_mem_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/shared_mem/ip/shared_mem_axi_smc_0/shared_mem_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shared_mem_axi_smc_0 || ORIG_REF_NAME==shared_mem_axi_smc_0} -quiet] -quiet

# IP: bd/shared_mem/ip/shared_mem_rst_ps7_0_50M_0/shared_mem_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==shared_mem_rst_ps7_0_50M_0 || ORIG_REF_NAME==shared_mem_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/capstone/shared_mem/shared_mem.gen/sources_1/bd/shared_mem/shared_mem_ooc.xdc
